### ISSUE TITLE
Credential error (?)

### ISSUE THREAD

**Issue by Lautenschlager-id** [entibo/miceditor-map-preview#1]
Hello. Since the beginning of the week I have been receiving the response `"Invalid client_id"` with code 500. Is there any specific reason or a credential header I should include in my requests?

**Comment by entibo** [comment]
Hi. 
This seems to be an issue with the imgur API.
Trying the same request a few times eventually works though...

**Comment by entibo** [comment]
Heard back from Imgur support and it's fixed!
